# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=mnist_optuna experiment=example

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric: "val/acc"

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: null

    # name of the study to persist optimization results
    study_name: classification_calib

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: maximize

    # total number of runs that will be executed
    n_trials: 100

    # choose Optuna hyperparameter sampler
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 12345
      n_startup_trials: 15 # number of random sampling runs before optimization starts

    # define range of hyperparameters
    params:
      model.reg_criterion.bandwidths.x: tag(log, interval(0.001, 200))
      model.reg_criterion.bandwidths.y: tag(log, interval(0.001, 200))
      model.reg_criterion.scalers.x: tag(log, interval(0.01, 10))
      model.reg_criterion.scalers.y: tag(log, interval(0.01, 10))
      model.reg_criterion.loss_scalers: tag(log, interval(0.1, 1000))
      model.lr: tag(log, interval(0.000001, 0.01))

      
