_target_: src.models.lightening_module.ClassificationLitModule
lr: 0.001
weight_decay: 0.0005

net:
  _target_: "src.models.components.models.CalibNet"
  input_size: 102
  output_size: 1
  edepth: 2
  ewidths: 512 # generator 
  adepth: 2
  awidths: 256  # discriminator


task_criterion:
  _target_: torch.nn.CrossEntropyLoss

calibrator:
  _target_: src.calibration.calibration.TemperatureScaling