_target_: "src.models.fair_lightening_module.fair_ClassificationLitModule"
net:
  _target_: "src.models.components.models.LaftrNet"
  input_size: 102
  output_size: 2
  zdim: 16
  edepth: 2
  ewidths: 32
  cdepth: 2
  cwidths: 32 
  adepth: 2
  awidths: 32
  num_groups: 2
lr: 0.001
weight_decay: 0.0005


criterion:
  _target_: torch.nn.CrossEntropyLoss

